logging:
  level: DEBUG

#Servidores de recurso free-commerce

produto:
    service: http://localhost:8090
    version: /v1
    context: /produto
    cadastrar: ?lojaId=
    buscarProdutoPorId: ?produtoId=
    buscarProdutosPorLoja: /produto?lojaId=%s&page=%s&size=%s
    buscarPorNomeParecido: ?page=%s&size=%s&produtoNome=%s
    categoria: categoria=
    nome: produtoNome=
    page: page=
    size: size=
    orderBy: order=
    novo: novo=
    cidade: cidade=
    lojaId: lojaId=


carrinho:
    service: http://localhost:8090
    version: /v1
    context: /carrinho
    buscarCarrinhoDeCompras: ?cookieId=%s




